// GENERATED CODE — DO NOT EDIT BY HAND.
// Regenerate with:
//   dart run pigeon --input pigeons/colada_api.dart && dart format lib/src/messages.g.dart
// Schema: pigeons/colada_api.dart
// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Configuration handed to the native SDK at startup.
///
/// `debug`, `strictMode` and `existingDeviceId` have no native equivalent on
/// iOS. They still cross, because the iOS bridge holds them itself: they decide
/// whether an unsupported capability warns or throws, and whether the bridge
/// emits verbose log records.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NativeConfig: Hashable, CustomStringConvertible {
  var publicTenantKey: String
  var debug: Bool
  var strictMode: Bool
  var automaticDeepLinkForwarding: Bool
  var existingDeviceId: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeConfig? {
    let publicTenantKey = pigeonVar_list[0] as! String
    let debug = pigeonVar_list[1] as! Bool
    let strictMode = pigeonVar_list[2] as! Bool
    let automaticDeepLinkForwarding = pigeonVar_list[3] as! Bool
    let existingDeviceId: String? = nilOrValue(pigeonVar_list[4])

    return NativeConfig(
      publicTenantKey: publicTenantKey,
      debug: debug,
      strictMode: strictMode,
      automaticDeepLinkForwarding: automaticDeepLinkForwarding,
      existingDeviceId: existingDeviceId
    )
  }
  func toList() -> [Any?] {
    return [
      publicTenantKey,
      debug,
      strictMode,
      automaticDeepLinkForwarding,
      existingDeviceId,
    ]
  }
  static func == (lhs: NativeConfig, rhs: NativeConfig) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.publicTenantKey, rhs.publicTenantKey) && MessagesPigeonInternal.deepEquals(lhs.debug, rhs.debug) && MessagesPigeonInternal.deepEquals(lhs.strictMode, rhs.strictMode) && MessagesPigeonInternal.deepEquals(lhs.automaticDeepLinkForwarding, rhs.automaticDeepLinkForwarding) && MessagesPigeonInternal.deepEquals(lhs.existingDeviceId, rhs.existingDeviceId)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeConfig")
    MessagesPigeonInternal.deepHash(value: publicTenantKey, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: debug, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: strictMode, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: automaticDeepLinkForwarding, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: existingDeviceId, hasher: &hasher)
  }

  public var description: String {
    return "NativeConfig(publicTenantKey: \(String(describing: publicTenantKey)), debug: \(String(describing: debug)), strictMode: \(String(describing: strictMode)), automaticDeepLinkForwarding: \(String(describing: automaticDeepLinkForwarding)), existingDeviceId: \(String(describing: existingDeviceId)))"
  }
}

/// Deferred deep-link target.
///
/// On iOS this is synthesised by the bridge from the flat handshake result's
/// `attributionStoreId` / `attributionMenuItemId` / `isCoffeeSubscription`, so
/// the Dart layer sees one shape on both platforms. `extras` is always empty
/// there — the native iOS SDK does not surface additional parameters.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NativeDeferredDeepLink: Hashable, CustomStringConvertible {
  var storeId: String? = nil
  var menuItemId: String? = nil
  var isCoffeeSubscription: Bool
  var extras: [String: String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeDeferredDeepLink? {
    let storeId: String? = nilOrValue(pigeonVar_list[0])
    let menuItemId: String? = nilOrValue(pigeonVar_list[1])
    let isCoffeeSubscription = pigeonVar_list[2] as! Bool
    let extras = pigeonVar_list[3] as! [String: String]

    return NativeDeferredDeepLink(
      storeId: storeId,
      menuItemId: menuItemId,
      isCoffeeSubscription: isCoffeeSubscription,
      extras: extras
    )
  }
  func toList() -> [Any?] {
    return [
      storeId,
      menuItemId,
      isCoffeeSubscription,
      extras,
    ]
  }
  static func == (lhs: NativeDeferredDeepLink, rhs: NativeDeferredDeepLink) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.storeId, rhs.storeId) && MessagesPigeonInternal.deepEquals(lhs.menuItemId, rhs.menuItemId) && MessagesPigeonInternal.deepEquals(lhs.isCoffeeSubscription, rhs.isCoffeeSubscription) && MessagesPigeonInternal.deepEquals(lhs.extras, rhs.extras)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeDeferredDeepLink")
    MessagesPigeonInternal.deepHash(value: storeId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: menuItemId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: isCoffeeSubscription, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: extras, hasher: &hasher)
  }

  public var description: String {
    return "NativeDeferredDeepLink(storeId: \(String(describing: storeId)), menuItemId: \(String(describing: menuItemId)), isCoffeeSubscription: \(String(describing: isCoffeeSubscription)), extras: \(String(describing: extras)))"
  }
}

/// A resolved attribution.
///
/// `matchMethod` is the raw backend string — see the note at the top of this
/// file. `extras` carries anything the backend returned that neither SDK
/// models; on iOS the bridge also folds the native result's diagnostic fields
/// (`asn`, `osVersion`, `screenResolution`, `rawLink`) in here, since they have
/// no Android counterpart.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NativeAttribution: Hashable, CustomStringConvertible {
  var matched: Bool
  var matchMethod: String? = nil
  var utmSource: String? = nil
  var utmCampaign: String? = nil
  var utmMedium: String? = nil
  var utmContent: String? = nil
  var utmTerm: String? = nil
  var clickId: String? = nil
  var attributionId: String? = nil
  var tenantKey: String? = nil
  var deferredDeepLink: NativeDeferredDeepLink? = nil
  var extras: [String: Any?]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeAttribution? {
    let matched = pigeonVar_list[0] as! Bool
    let matchMethod: String? = nilOrValue(pigeonVar_list[1])
    let utmSource: String? = nilOrValue(pigeonVar_list[2])
    let utmCampaign: String? = nilOrValue(pigeonVar_list[3])
    let utmMedium: String? = nilOrValue(pigeonVar_list[4])
    let utmContent: String? = nilOrValue(pigeonVar_list[5])
    let utmTerm: String? = nilOrValue(pigeonVar_list[6])
    let clickId: String? = nilOrValue(pigeonVar_list[7])
    let attributionId: String? = nilOrValue(pigeonVar_list[8])
    let tenantKey: String? = nilOrValue(pigeonVar_list[9])
    let deferredDeepLink: NativeDeferredDeepLink? = nilOrValue(pigeonVar_list[10])
    let extras = pigeonVar_list[11] as! [String: Any?]

    return NativeAttribution(
      matched: matched,
      matchMethod: matchMethod,
      utmSource: utmSource,
      utmCampaign: utmCampaign,
      utmMedium: utmMedium,
      utmContent: utmContent,
      utmTerm: utmTerm,
      clickId: clickId,
      attributionId: attributionId,
      tenantKey: tenantKey,
      deferredDeepLink: deferredDeepLink,
      extras: extras
    )
  }
  func toList() -> [Any?] {
    return [
      matched,
      matchMethod,
      utmSource,
      utmCampaign,
      utmMedium,
      utmContent,
      utmTerm,
      clickId,
      attributionId,
      tenantKey,
      deferredDeepLink,
      extras,
    ]
  }
  static func == (lhs: NativeAttribution, rhs: NativeAttribution) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.matched, rhs.matched) && MessagesPigeonInternal.deepEquals(lhs.matchMethod, rhs.matchMethod) && MessagesPigeonInternal.deepEquals(lhs.utmSource, rhs.utmSource) && MessagesPigeonInternal.deepEquals(lhs.utmCampaign, rhs.utmCampaign) && MessagesPigeonInternal.deepEquals(lhs.utmMedium, rhs.utmMedium) && MessagesPigeonInternal.deepEquals(lhs.utmContent, rhs.utmContent) && MessagesPigeonInternal.deepEquals(lhs.utmTerm, rhs.utmTerm) && MessagesPigeonInternal.deepEquals(lhs.clickId, rhs.clickId) && MessagesPigeonInternal.deepEquals(lhs.attributionId, rhs.attributionId) && MessagesPigeonInternal.deepEquals(lhs.tenantKey, rhs.tenantKey) && MessagesPigeonInternal.deepEquals(lhs.deferredDeepLink, rhs.deferredDeepLink) && MessagesPigeonInternal.deepEquals(lhs.extras, rhs.extras)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeAttribution")
    MessagesPigeonInternal.deepHash(value: matched, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: matchMethod, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: utmSource, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: utmCampaign, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: utmMedium, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: utmContent, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: utmTerm, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: clickId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: attributionId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: tenantKey, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: deferredDeepLink, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: extras, hasher: &hasher)
  }

  public var description: String {
    return "NativeAttribution(matched: \(String(describing: matched)), matchMethod: \(String(describing: matchMethod)), utmSource: \(String(describing: utmSource)), utmCampaign: \(String(describing: utmCampaign)), utmMedium: \(String(describing: utmMedium)), utmContent: \(String(describing: utmContent)), utmTerm: \(String(describing: utmTerm)), clickId: \(String(describing: clickId)), attributionId: \(String(describing: attributionId)), tenantKey: \(String(describing: tenantKey)), deferredDeepLink: \(String(describing: deferredDeepLink)), extras: \(String(describing: extras)))"
  }
}

/// One diagnostic log record.
///
/// `level` is a String for the same reason `matchMethod` is — an unrecognised
/// level must degrade, never throw, because this is the channel that reports
/// problems and it cannot be the thing that fails.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NativeLogRecord: Hashable, CustomStringConvertible {
  var level: String
  var message: String
  var error: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeLogRecord? {
    let level = pigeonVar_list[0] as! String
    let message = pigeonVar_list[1] as! String
    let error: String? = nilOrValue(pigeonVar_list[2])

    return NativeLogRecord(
      level: level,
      message: message,
      error: error
    )
  }
  func toList() -> [Any?] {
    return [
      level,
      message,
      error,
    ]
  }
  static func == (lhs: NativeLogRecord, rhs: NativeLogRecord) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.level, rhs.level) && MessagesPigeonInternal.deepEquals(lhs.message, rhs.message) && MessagesPigeonInternal.deepEquals(lhs.error, rhs.error)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeLogRecord")
    MessagesPigeonInternal.deepHash(value: level, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: message, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: error, hasher: &hasher)
  }

  public var description: String {
    return "NativeLogRecord(level: \(String(describing: level)), message: \(String(describing: message)), error: \(String(describing: error)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return NativeConfig.fromList(self.readValue() as! [Any?])
    case 130:
      return NativeDeferredDeepLink.fromList(self.readValue() as! [Any?])
    case 131:
      return NativeAttribution.fromList(self.readValue() as! [Any?])
    case 132:
      return NativeLogRecord.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? NativeConfig {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? NativeDeferredDeepLink {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? NativeAttribution {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? NativeLogRecord {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}

var messagesPigeonMethodCodec = FlutterStandardMethodCodec(readerWriter: MessagesPigeonCodecReaderWriter());


/// Calls from Dart into the native SDK.
///
/// Every method is `@async`: the iOS SDK is actor-isolated and genuinely
/// asynchronous, and Android must not block the platform thread. Errors are
/// raised natively with a Colada error code, which the Dart layer maps back to
/// the typed exceptions in `lib/src/exceptions.dart`.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ColadaHostApi {
  /// Starts the native SDK. Argument validation has already happened in Dart.
  func initialize(config: NativeConfig, completion: @escaping (Result<Void, Error>) -> Void)
  /// Whether the native SDK is running.
  ///
  /// On iOS there is no native equivalent, so the bridge reports its own flag,
  /// set once `configure()` returns without throwing.
  func isInitialized(completion: @escaping (Result<Bool, Error>) -> Void)
  /// This device's stable Colada identifier, or null before initialize.
  func deviceId(completion: @escaping (Result<String?, Error>) -> Void)
  /// Associates subsequent events with a user.
  func setUser(externalUserId: String, completion: @escaping (Result<Void, Error>) -> Void)
  /// Clears the current user.
  ///
  /// Maps to `clearUser()` on Android and `setExternalUserId(nil)` on iOS.
  func clearUser(completion: @escaping (Result<Void, Error>) -> Void)
  /// Reports an event by wire name plus a flat metadata map.
  ///
  /// This shape is deliberate: the native Android SDK already exposes
  /// `track(eventName, metadata)` and `ColadaEvent.of(name, map)` built for
  /// exactly this, so the bridge reuses its validation rather than duplicating
  /// it. The iOS bridge does more work here — it maps the name onto the fixed
  /// `AttributionEventName` enum, splits the metadata into the native SDK's
  /// fixed struct, routes a registration carrying user data to
  /// `reportRegistration`, and reports any key it could not transmit.
  func track(eventName: String, metadata: [String: Any?], completion: @escaping (Result<Void, Error>) -> Void)
  /// Requests immediate delivery of queued events.
  func flush(completion: @escaping (Result<Void, Error>) -> Void)
  /// The attribution resolved so far, or null.
  func currentAttribution(completion: @escaping (Result<NativeAttribution?, Error>) -> Void)
  /// Consumes the pending deferred deep link. Returns null on a second call.
  func consumeDeferredDeepLink(completion: @escaping (Result<NativeDeferredDeepLink?, Error>) -> Void)
  /// Reports a deep link.
  ///
  /// Normally called by the plugin itself; only reaches here from Dart when the
  /// host opted out of automatic forwarding.
  func handleDeepLink(url: String, completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ColadaHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `ColadaHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ColadaHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Starts the native SDK. Argument validation has already happened in Dart.
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.colada_sdk.ColadaHostApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! NativeConfig
        api.initialize(config: configArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    /// Whether the native SDK is running.
    ///
    /// On iOS there is no native equivalent, so the bridge reports its own flag,
    /// set once `configure()` returns without throwing.
    let isInitializedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.colada_sdk.ColadaHostApi.isInitialized\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isInitializedChannel.setMessageHandler { _, reply in
        api.isInitialized { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      isInitializedChannel.setMessageHandler(nil)
    }
    /// This device's stable Colada identifier, or null before initialize.
    let deviceIdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.colada_sdk.ColadaHostApi.deviceId\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      deviceIdChannel.setMessageHandler { _, reply in
        api.deviceId { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      deviceIdChannel.setMessageHandler(nil)
    }
    /// Associates subsequent events with a user.
    let setUserChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.colada_sdk.ColadaHostApi.setUser\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setUserChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let externalUserIdArg = args[0] as! String
        api.setUser(externalUserId: externalUserIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setUserChannel.setMessageHandler(nil)
    }
    /// Clears the current user.
    ///
    /// Maps to `clearUser()` on Android and `setExternalUserId(nil)` on iOS.
    let clearUserChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.colada_sdk.ColadaHostApi.clearUser\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearUserChannel.setMessageHandler { _, reply in
        api.clearUser { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      clearUserChannel.setMessageHandler(nil)
    }
    /// Reports an event by wire name plus a flat metadata map.
    ///
    /// This shape is deliberate: the native Android SDK already exposes
    /// `track(eventName, metadata)` and `ColadaEvent.of(name, map)` built for
    /// exactly this, so the bridge reuses its validation rather than duplicating
    /// it. The iOS bridge does more work here — it maps the name onto the fixed
    /// `AttributionEventName` enum, splits the metadata into the native SDK's
    /// fixed struct, routes a registration carrying user data to
    /// `reportRegistration`, and reports any key it could not transmit.
    let trackChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.colada_sdk.ColadaHostApi.track\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      trackChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let eventNameArg = args[0] as! String
        let metadataArg = args[1] as! [String: Any?]
        api.track(eventName: eventNameArg, metadata: metadataArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      trackChannel.setMessageHandler(nil)
    }
    /// Requests immediate delivery of queued events.
    let flushChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.colada_sdk.ColadaHostApi.flush\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      flushChannel.setMessageHandler { _, reply in
        api.flush { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      flushChannel.setMessageHandler(nil)
    }
    /// The attribution resolved so far, or null.
    let currentAttributionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.colada_sdk.ColadaHostApi.currentAttribution\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      currentAttributionChannel.setMessageHandler { _, reply in
        api.currentAttribution { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      currentAttributionChannel.setMessageHandler(nil)
    }
    /// Consumes the pending deferred deep link. Returns null on a second call.
    let consumeDeferredDeepLinkChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.colada_sdk.ColadaHostApi.consumeDeferredDeepLink\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      consumeDeferredDeepLinkChannel.setMessageHandler { _, reply in
        api.consumeDeferredDeepLink { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      consumeDeferredDeepLinkChannel.setMessageHandler(nil)
    }
    /// Reports a deep link.
    ///
    /// Normally called by the plugin itself; only reaches here from Dart when the
    /// host opted out of automatic forwarding.
    let handleDeepLinkChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.colada_sdk.ColadaHostApi.handleDeepLink\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      handleDeepLinkChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlArg = args[0] as! String
        api.handleDeepLink(url: urlArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      handleDeepLinkChannel.setMessageHandler(nil)
    }
  }
}

private class PigeonStreamHandler<ReturnType>: NSObject, FlutterStreamHandler {
  private let wrapper: PigeonEventChannelWrapper<ReturnType>
  private var pigeonSink: PigeonEventSink<ReturnType>? = nil

  init(wrapper: PigeonEventChannelWrapper<ReturnType>) {
    self.wrapper = wrapper
  }

  func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink)
    -> FlutterError?
  {
    pigeonSink = PigeonEventSink<ReturnType>(events)
    wrapper.onListen(withArguments: arguments, sink: pigeonSink!)
    return nil
  }

  func onCancel(withArguments arguments: Any?) -> FlutterError? {
    pigeonSink = nil
    wrapper.onCancel(withArguments: arguments)
    return nil
  }
}

class PigeonEventChannelWrapper<ReturnType> {
  func onListen(withArguments arguments: Any?, sink: PigeonEventSink<ReturnType>) {}
  func onCancel(withArguments arguments: Any?) {}
}

class PigeonEventSink<ReturnType> {
  private let sink: FlutterEventSink

  init(_ sink: @escaping FlutterEventSink) {
    self.sink = sink
  }

  func success(_ value: ReturnType) {
    sink(value)
  }

  func error(code: String, message: String?, details: Any?) {
    sink(FlutterError(code: code, message: message, details: details))
  }

  func endOfStream() {
    sink(FlutterEndOfEventStream)
  }

}

/// Streams from native into Dart.
///
/// Both replay their most recent value to a new listener, because both native
/// SDKs do: attribution typically resolves before any UI is ready to subscribe,
/// and without the replay a deferred deep link would work on a slow network and
/// fail on a fast one.
class AttributionResolvedStreamHandler: PigeonEventChannelWrapper<NativeAttribution> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: AttributionResolvedStreamHandler) {
    var channelName = "dev.flutter.pigeon.colada_sdk.ColadaEventChannels.attributionResolved"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<NativeAttribution>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: messagesPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
class LogEmittedStreamHandler: PigeonEventChannelWrapper<NativeLogRecord> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: LogEmittedStreamHandler) {
    var channelName = "dev.flutter.pigeon.colada_sdk.ColadaEventChannels.logEmitted"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<NativeLogRecord>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: messagesPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
