// GENERATED CODE — DO NOT EDIT BY HAND.
// Regenerate with:
//   dart run pigeon --input pigeons/colada_api.dart && dart format lib/src/messages.g.dart
// Schema: pigeons/colada_api.dart
// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package io.coladaapp.sdk.flutter

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * Configuration handed to the native SDK at startup.
 *
 * `debug`, `strictMode` and `existingDeviceId` have no native equivalent on
 * iOS. They still cross, because the iOS bridge holds them itself: they decide
 * whether an unsupported capability warns or throws, and whether the bridge
 * emits verbose log records.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NativeConfig (
  val publicTenantKey: String,
  val debug: Boolean,
  val strictMode: Boolean,
  val automaticDeepLinkForwarding: Boolean,
  val existingDeviceId: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeConfig {
      val publicTenantKey = pigeonVar_list[0] as String
      val debug = pigeonVar_list[1] as Boolean
      val strictMode = pigeonVar_list[2] as Boolean
      val automaticDeepLinkForwarding = pigeonVar_list[3] as Boolean
      val existingDeviceId = pigeonVar_list[4] as String?
      return NativeConfig(publicTenantKey, debug, strictMode, automaticDeepLinkForwarding, existingDeviceId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      publicTenantKey,
      debug,
      strictMode,
      automaticDeepLinkForwarding,
      existingDeviceId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeConfig
    return MessagesPigeonUtils.deepEquals(this.publicTenantKey, other.publicTenantKey) && MessagesPigeonUtils.deepEquals(this.debug, other.debug) && MessagesPigeonUtils.deepEquals(this.strictMode, other.strictMode) && MessagesPigeonUtils.deepEquals(this.automaticDeepLinkForwarding, other.automaticDeepLinkForwarding) && MessagesPigeonUtils.deepEquals(this.existingDeviceId, other.existingDeviceId)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.publicTenantKey)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.debug)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.strictMode)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.automaticDeepLinkForwarding)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.existingDeviceId)
    return result
  }
  override fun toString(): String {
    return "NativeConfig(publicTenantKey=$publicTenantKey, debug=$debug, strictMode=$strictMode, automaticDeepLinkForwarding=$automaticDeepLinkForwarding, existingDeviceId=$existingDeviceId)"
  }
}

/**
 * Deferred deep-link target.
 *
 * On iOS this is synthesised by the bridge from the flat handshake result's
 * `attributionStoreId` / `attributionMenuItemId` / `isCoffeeSubscription`, so
 * the Dart layer sees one shape on both platforms. `extras` is always empty
 * there — the native iOS SDK does not surface additional parameters.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NativeDeferredDeepLink (
  val storeId: String? = null,
  val menuItemId: String? = null,
  val isCoffeeSubscription: Boolean,
  val extras: Map<String, String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeDeferredDeepLink {
      val storeId = pigeonVar_list[0] as String?
      val menuItemId = pigeonVar_list[1] as String?
      val isCoffeeSubscription = pigeonVar_list[2] as Boolean
      val extras = pigeonVar_list[3] as Map<String, String>
      return NativeDeferredDeepLink(storeId, menuItemId, isCoffeeSubscription, extras)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      storeId,
      menuItemId,
      isCoffeeSubscription,
      extras,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeDeferredDeepLink
    return MessagesPigeonUtils.deepEquals(this.storeId, other.storeId) && MessagesPigeonUtils.deepEquals(this.menuItemId, other.menuItemId) && MessagesPigeonUtils.deepEquals(this.isCoffeeSubscription, other.isCoffeeSubscription) && MessagesPigeonUtils.deepEquals(this.extras, other.extras)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.storeId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.menuItemId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.isCoffeeSubscription)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.extras)
    return result
  }
  override fun toString(): String {
    return "NativeDeferredDeepLink(storeId=$storeId, menuItemId=$menuItemId, isCoffeeSubscription=$isCoffeeSubscription, extras=$extras)"
  }
}

/**
 * A resolved attribution.
 *
 * `matchMethod` is the raw backend string — see the note at the top of this
 * file. `extras` carries anything the backend returned that neither SDK
 * models; on iOS the bridge also folds the native result's diagnostic fields
 * (`asn`, `osVersion`, `screenResolution`, `rawLink`) in here, since they have
 * no Android counterpart.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NativeAttribution (
  val matched: Boolean,
  val matchMethod: String? = null,
  val utmSource: String? = null,
  val utmCampaign: String? = null,
  val utmMedium: String? = null,
  val utmContent: String? = null,
  val utmTerm: String? = null,
  val clickId: String? = null,
  val attributionId: String? = null,
  val tenantKey: String? = null,
  val deferredDeepLink: NativeDeferredDeepLink? = null,
  val extras: Map<String, Any?>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeAttribution {
      val matched = pigeonVar_list[0] as Boolean
      val matchMethod = pigeonVar_list[1] as String?
      val utmSource = pigeonVar_list[2] as String?
      val utmCampaign = pigeonVar_list[3] as String?
      val utmMedium = pigeonVar_list[4] as String?
      val utmContent = pigeonVar_list[5] as String?
      val utmTerm = pigeonVar_list[6] as String?
      val clickId = pigeonVar_list[7] as String?
      val attributionId = pigeonVar_list[8] as String?
      val tenantKey = pigeonVar_list[9] as String?
      val deferredDeepLink = pigeonVar_list[10] as NativeDeferredDeepLink?
      val extras = pigeonVar_list[11] as Map<String, Any?>
      return NativeAttribution(matched, matchMethod, utmSource, utmCampaign, utmMedium, utmContent, utmTerm, clickId, attributionId, tenantKey, deferredDeepLink, extras)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      matched,
      matchMethod,
      utmSource,
      utmCampaign,
      utmMedium,
      utmContent,
      utmTerm,
      clickId,
      attributionId,
      tenantKey,
      deferredDeepLink,
      extras,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeAttribution
    return MessagesPigeonUtils.deepEquals(this.matched, other.matched) && MessagesPigeonUtils.deepEquals(this.matchMethod, other.matchMethod) && MessagesPigeonUtils.deepEquals(this.utmSource, other.utmSource) && MessagesPigeonUtils.deepEquals(this.utmCampaign, other.utmCampaign) && MessagesPigeonUtils.deepEquals(this.utmMedium, other.utmMedium) && MessagesPigeonUtils.deepEquals(this.utmContent, other.utmContent) && MessagesPigeonUtils.deepEquals(this.utmTerm, other.utmTerm) && MessagesPigeonUtils.deepEquals(this.clickId, other.clickId) && MessagesPigeonUtils.deepEquals(this.attributionId, other.attributionId) && MessagesPigeonUtils.deepEquals(this.tenantKey, other.tenantKey) && MessagesPigeonUtils.deepEquals(this.deferredDeepLink, other.deferredDeepLink) && MessagesPigeonUtils.deepEquals(this.extras, other.extras)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.matched)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.matchMethod)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.utmSource)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.utmCampaign)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.utmMedium)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.utmContent)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.utmTerm)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.clickId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.attributionId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.tenantKey)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.deferredDeepLink)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.extras)
    return result
  }
  override fun toString(): String {
    return "NativeAttribution(matched=$matched, matchMethod=$matchMethod, utmSource=$utmSource, utmCampaign=$utmCampaign, utmMedium=$utmMedium, utmContent=$utmContent, utmTerm=$utmTerm, clickId=$clickId, attributionId=$attributionId, tenantKey=$tenantKey, deferredDeepLink=$deferredDeepLink, extras=$extras)"
  }
}

/**
 * One diagnostic log record.
 *
 * `level` is a String for the same reason `matchMethod` is — an unrecognised
 * level must degrade, never throw, because this is the channel that reports
 * problems and it cannot be the thing that fails.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NativeLogRecord (
  val level: String,
  val message: String,
  val error: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeLogRecord {
      val level = pigeonVar_list[0] as String
      val message = pigeonVar_list[1] as String
      val error = pigeonVar_list[2] as String?
      return NativeLogRecord(level, message, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      level,
      message,
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeLogRecord
    return MessagesPigeonUtils.deepEquals(this.level, other.level) && MessagesPigeonUtils.deepEquals(this.message, other.message) && MessagesPigeonUtils.deepEquals(this.error, other.error)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.level)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.message)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.error)
    return result
  }
  override fun toString(): String {
    return "NativeLogRecord(level=$level, message=$message, error=$error)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeConfig.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeDeferredDeepLink.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeAttribution.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeLogRecord.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is NativeConfig -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is NativeDeferredDeepLink -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is NativeAttribution -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is NativeLogRecord -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

val MessagesPigeonMethodCodec = StandardMethodCodec(MessagesPigeonCodec())


/**
 * Calls from Dart into the native SDK.
 *
 * Every method is `@async`: the iOS SDK is actor-isolated and genuinely
 * asynchronous, and Android must not block the platform thread. Errors are
 * raised natively with a Colada error code, which the Dart layer maps back to
 * the typed exceptions in `lib/src/exceptions.dart`.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface ColadaHostApi {
  /** Starts the native SDK. Argument validation has already happened in Dart. */
  fun initialize(config: NativeConfig, callback: (Result<Unit>) -> Unit)
  /**
   * Whether the native SDK is running.
   *
   * On iOS there is no native equivalent, so the bridge reports its own flag,
   * set once `configure()` returns without throwing.
   */
  fun isInitialized(callback: (Result<Boolean>) -> Unit)
  /** This device's stable Colada identifier, or null before initialize. */
  fun deviceId(callback: (Result<String?>) -> Unit)
  /** Associates subsequent events with a user. */
  fun setUser(externalUserId: String, callback: (Result<Unit>) -> Unit)
  /**
   * Clears the current user.
   *
   * Maps to `clearUser()` on Android and `setExternalUserId(nil)` on iOS.
   */
  fun clearUser(callback: (Result<Unit>) -> Unit)
  /**
   * Reports an event by wire name plus a flat metadata map.
   *
   * This shape is deliberate: the native Android SDK already exposes
   * `track(eventName, metadata)` and `ColadaEvent.of(name, map)` built for
   * exactly this, so the bridge reuses its validation rather than duplicating
   * it. The iOS bridge does more work here — it maps the name onto the fixed
   * `AttributionEventName` enum, splits the metadata into the native SDK's
   * fixed struct, routes a registration carrying user data to
   * `reportRegistration`, and reports any key it could not transmit.
   */
  fun track(eventName: String, metadata: Map<String, Any?>, callback: (Result<Unit>) -> Unit)
  /** Requests immediate delivery of queued events. */
  fun flush(callback: (Result<Unit>) -> Unit)
  /** The attribution resolved so far, or null. */
  fun currentAttribution(callback: (Result<NativeAttribution?>) -> Unit)
  /** Consumes the pending deferred deep link. Returns null on a second call. */
  fun consumeDeferredDeepLink(callback: (Result<NativeDeferredDeepLink?>) -> Unit)
  /**
   * Reports a deep link.
   *
   * Normally called by the plugin itself; only reaches here from Dart when the
   * host opted out of automatic forwarding.
   */
  fun handleDeepLink(url: String, callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by ColadaHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `ColadaHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ColadaHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.colada_sdk.ColadaHostApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as NativeConfig
            api.initialize(configArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.colada_sdk.ColadaHostApi.isInitialized$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.isInitialized{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.colada_sdk.ColadaHostApi.deviceId$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.deviceId{ result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.colada_sdk.ColadaHostApi.setUser$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val externalUserIdArg = args[0] as String
            api.setUser(externalUserIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.colada_sdk.ColadaHostApi.clearUser$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.clearUser{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.colada_sdk.ColadaHostApi.track$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val eventNameArg = args[0] as String
            val metadataArg = args[1] as Map<String, Any?>
            api.track(eventNameArg, metadataArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.colada_sdk.ColadaHostApi.flush$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.flush{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.colada_sdk.ColadaHostApi.currentAttribution$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.currentAttribution{ result: Result<NativeAttribution?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.colada_sdk.ColadaHostApi.consumeDeferredDeepLink$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.consumeDeferredDeepLink{ result: Result<NativeDeferredDeepLink?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.colada_sdk.ColadaHostApi.handleDeepLink$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            api.handleDeepLink(urlArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}

private class MessagesPigeonStreamHandler<T>(
    val wrapper: MessagesPigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface MessagesPigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}
      
/**
 * Streams from native into Dart.
 *
 * Both replay their most recent value to a new listener, because both native
 * SDKs do: attribution typically resolves before any UI is ready to subscribe,
 * and without the replay a deferred deep link would work on a slow network and
 * fail on a fast one.
 */
abstract class AttributionResolvedStreamHandler : MessagesPigeonEventChannelWrapper<NativeAttribution> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: AttributionResolvedStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.colada_sdk.ColadaEventChannels.attributionResolved"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = MessagesPigeonStreamHandler<NativeAttribution>(streamHandler)
      EventChannel(messenger, channelName, MessagesPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from MessagesPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<NativeAttribution>) {}

override fun onCancel(p0: Any?) {}
}
      
abstract class LogEmittedStreamHandler : MessagesPigeonEventChannelWrapper<NativeLogRecord> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: LogEmittedStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.colada_sdk.ColadaEventChannels.logEmitted"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = MessagesPigeonStreamHandler<NativeLogRecord>(streamHandler)
      EventChannel(messenger, channelName, MessagesPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from MessagesPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<NativeLogRecord>) {}

override fun onCancel(p0: Any?) {}
}
      
