// GENERATED CODE — DO NOT EDIT BY HAND.
// Regenerate with:
//   dart run pigeon --input pigeons/colada_api.dart && dart format lib/src/messages.g.dart
// Schema: pigeons/colada_api.dart
// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// Configuration handed to the native SDK at startup.
///
/// `debug`, `strictMode` and `existingDeviceId` have no native equivalent on
/// iOS. They still cross, because the iOS bridge holds them itself: they decide
/// whether an unsupported capability warns or throws, and whether the bridge
/// emits verbose log records.
class NativeConfig {
  NativeConfig({
    required this.publicTenantKey,
    required this.debug,
    required this.strictMode,
    required this.automaticDeepLinkForwarding,
    this.existingDeviceId,
  });

  String publicTenantKey;

  bool debug;

  bool strictMode;

  bool automaticDeepLinkForwarding;

  String? existingDeviceId;

  List<Object?> _toList() {
    return <Object?>[
      publicTenantKey,
      debug,
      strictMode,
      automaticDeepLinkForwarding,
      existingDeviceId,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NativeConfig decode(Object result) {
    result as List<Object?>;
    return NativeConfig(
      publicTenantKey: result[0]! as String,
      debug: result[1]! as bool,
      strictMode: result[2]! as bool,
      automaticDeepLinkForwarding: result[3]! as bool,
      existingDeviceId: result[4] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(publicTenantKey, other.publicTenantKey) &&
        _deepEquals(debug, other.debug) &&
        _deepEquals(strictMode, other.strictMode) &&
        _deepEquals(
            automaticDeepLinkForwarding, other.automaticDeepLinkForwarding) &&
        _deepEquals(existingDeviceId, other.existingDeviceId);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeConfig(publicTenantKey: $publicTenantKey, debug: $debug, strictMode: $strictMode, automaticDeepLinkForwarding: $automaticDeepLinkForwarding, existingDeviceId: $existingDeviceId)';
  }
}

/// Deferred deep-link target.
///
/// The destination is carried entirely in [extras]. Both native SDKs now expose
/// the deferred deep link as a single `Map<String, String>`: `storeId`,
/// `menuItemId` and `isCoffeeSubscription` appear there under those exact keys
/// when present, alongside any tenant-specific destination fields. There are no
/// typed destination properties anymore, so the Dart layer sees one shape on
/// both platforms.
class NativeDeferredDeepLink {
  NativeDeferredDeepLink({
    required this.extras,
  });

  Map<String, String> extras;

  List<Object?> _toList() {
    return <Object?>[
      extras,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NativeDeferredDeepLink decode(Object result) {
    result as List<Object?>;
    return NativeDeferredDeepLink(
      extras: (result[0]! as Map<Object?, Object?>).cast<String, String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeDeferredDeepLink || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(extras, other.extras);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeDeferredDeepLink(extras: $extras)';
  }
}

/// A resolved attribution.
///
/// `matchMethod` is the raw backend string — see the note at the top of this
/// file. `extras` carries the campaign destination and any tenant params as a
/// string map — the same map [deferredDeepLink] exposes — so a backend field
/// neither SDK models is still readable. (It is typed `Object?` here only to
/// keep the public Dart model's `extras` type stable; both SDKs send strings.)
class NativeAttribution {
  NativeAttribution({
    required this.matched,
    this.matchMethod,
    this.utmSource,
    this.utmCampaign,
    this.utmMedium,
    this.utmContent,
    this.utmTerm,
    this.clickId,
    this.attributionId,
    this.tenantKey,
    this.deferredDeepLink,
    required this.extras,
  });

  bool matched;

  String? matchMethod;

  String? utmSource;

  String? utmCampaign;

  String? utmMedium;

  String? utmContent;

  String? utmTerm;

  String? clickId;

  String? attributionId;

  String? tenantKey;

  NativeDeferredDeepLink? deferredDeepLink;

  Map<String, Object?> extras;

  List<Object?> _toList() {
    return <Object?>[
      matched,
      matchMethod,
      utmSource,
      utmCampaign,
      utmMedium,
      utmContent,
      utmTerm,
      clickId,
      attributionId,
      tenantKey,
      deferredDeepLink,
      extras,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NativeAttribution decode(Object result) {
    result as List<Object?>;
    return NativeAttribution(
      matched: result[0]! as bool,
      matchMethod: result[1] as String?,
      utmSource: result[2] as String?,
      utmCampaign: result[3] as String?,
      utmMedium: result[4] as String?,
      utmContent: result[5] as String?,
      utmTerm: result[6] as String?,
      clickId: result[7] as String?,
      attributionId: result[8] as String?,
      tenantKey: result[9] as String?,
      deferredDeepLink: result[10] as NativeDeferredDeepLink?,
      extras: (result[11]! as Map<Object?, Object?>).cast<String, Object?>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeAttribution || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(matched, other.matched) &&
        _deepEquals(matchMethod, other.matchMethod) &&
        _deepEquals(utmSource, other.utmSource) &&
        _deepEquals(utmCampaign, other.utmCampaign) &&
        _deepEquals(utmMedium, other.utmMedium) &&
        _deepEquals(utmContent, other.utmContent) &&
        _deepEquals(utmTerm, other.utmTerm) &&
        _deepEquals(clickId, other.clickId) &&
        _deepEquals(attributionId, other.attributionId) &&
        _deepEquals(tenantKey, other.tenantKey) &&
        _deepEquals(deferredDeepLink, other.deferredDeepLink) &&
        _deepEquals(extras, other.extras);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeAttribution(matched: $matched, matchMethod: $matchMethod, utmSource: $utmSource, utmCampaign: $utmCampaign, utmMedium: $utmMedium, utmContent: $utmContent, utmTerm: $utmTerm, clickId: $clickId, attributionId: $attributionId, tenantKey: $tenantKey, deferredDeepLink: $deferredDeepLink, extras: $extras)';
  }
}

/// One diagnostic log record.
///
/// `level` is a String for the same reason `matchMethod` is — an unrecognised
/// level must degrade, never throw, because this is the channel that reports
/// problems and it cannot be the thing that fails.
class NativeLogRecord {
  NativeLogRecord({
    required this.level,
    required this.message,
    this.error,
  });

  String level;

  String message;

  String? error;

  List<Object?> _toList() {
    return <Object?>[
      level,
      message,
      error,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NativeLogRecord decode(Object result) {
    result as List<Object?>;
    return NativeLogRecord(
      level: result[0]! as String,
      message: result[1]! as String,
      error: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeLogRecord || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(level, other.level) &&
        _deepEquals(message, other.message) &&
        _deepEquals(error, other.error);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeLogRecord(level: $level, message: $message, error: $error)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is NativeConfig) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is NativeDeferredDeepLink) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is NativeAttribution) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is NativeLogRecord) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return NativeConfig.decode(readValue(buffer)!);
      case 130:
        return NativeDeferredDeepLink.decode(readValue(buffer)!);
      case 131:
        return NativeAttribution.decode(readValue(buffer)!);
      case 132:
        return NativeLogRecord.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec =
    StandardMethodCodec(_PigeonCodec());

/// Calls from Dart into the native SDK.
///
/// Every method is `@async`: the iOS SDK is actor-isolated and genuinely
/// asynchronous, and Android must not block the platform thread. Errors are
/// raised natively with a Colada error code, which the Dart layer maps back to
/// the typed exceptions in `lib/src/exceptions.dart`.
class ColadaHostApi {
  /// Constructor for [ColadaHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ColadaHostApi(
      {BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix =
            messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Starts the native SDK. Argument validation has already happened in Dart.
  Future<void> initialize(NativeConfig config) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.colada_sdk.ColadaHostApi.initialize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[config]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Whether the native SDK is running.
  ///
  /// On iOS there is no native equivalent, so the bridge reports its own flag,
  /// set once `configure()` returns without throwing.
  Future<bool> isInitialized() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.colada_sdk.ColadaHostApi.isInitialized$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// This device's stable Colada identifier, or null before initialize.
  Future<String?> deviceId() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.colada_sdk.ColadaHostApi.deviceId$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as String?;
  }

  /// Associates subsequent events with a user.
  Future<void> setUser(String externalUserId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.colada_sdk.ColadaHostApi.setUser$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[externalUserId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Clears the current user.
  ///
  /// Maps to `clearUser()` on Android and `setExternalUserId(nil)` on iOS.
  Future<void> clearUser() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.colada_sdk.ColadaHostApi.clearUser$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Reports an event by wire name plus a flat metadata map.
  ///
  /// This shape is deliberate: the native Android SDK already exposes
  /// `track(eventName, metadata)` and `ColadaEvent.of(name, map)` built for
  /// exactly this, so the bridge reuses its validation rather than duplicating
  /// it. The iOS bridge does more work here — it maps the name onto the fixed
  /// `AttributionEventName` enum, splits the metadata into the native SDK's
  /// fixed struct, routes a registration carrying user data to
  /// `reportRegistration`, and reports any key it could not transmit.
  Future<void> track(String eventName, Map<String, Object?> metadata) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.colada_sdk.ColadaHostApi.track$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[eventName, metadata]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Requests immediate delivery of queued events.
  Future<void> flush() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.colada_sdk.ColadaHostApi.flush$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// The attribution resolved so far, or null.
  Future<NativeAttribution?> currentAttribution() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.colada_sdk.ColadaHostApi.currentAttribution$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as NativeAttribution?;
  }

  /// Consumes the pending deferred deep link. Returns null on a second call.
  Future<NativeDeferredDeepLink?> consumeDeferredDeepLink() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.colada_sdk.ColadaHostApi.consumeDeferredDeepLink$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as NativeDeferredDeepLink?;
  }

  /// Reports a deep link.
  ///
  /// Normally called by the plugin itself; only reaches here from Dart when the
  /// host opted out of automatic forwarding.
  Future<void> handleDeepLink(String url) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.colada_sdk.ColadaHostApi.handleDeepLink$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[url]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}

/// Streams from native into Dart.
///
/// Both replay their most recent value to a new listener, because both native
/// SDKs do: attribution typically resolves before any UI is ready to subscribe,
/// and without the replay a deferred deep link would work on a slow network and
/// fail on a fast one.
/// Attribution results, as they resolve.
///
/// Returns a broadcast [Stream] of events from the `attributionResolved` event channel.
///
/// Each call to this method creates a new [EventChannel], so it should
/// not be called multiple times for the same `instanceName`. To deliver
/// events to multiple listeners, call this method once and listen to the
/// returned broadcast stream multiple times instead.
Stream<NativeAttribution> attributionResolved({String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel attributionResolvedChannel = EventChannel(
      'dev.flutter.pigeon.colada_sdk.ColadaEventChannels.attributionResolved$instanceName',
      pigeonMethodCodec);
  return attributionResolvedChannel
      .receiveBroadcastStream()
      .map((dynamic event) {
    return event as NativeAttribution;
  });
}

/// Diagnostic log records.
///
/// Both native SDKs now expose a log sink the bridge registers at
/// `configure`, so records come from the native SDK on Android and iOS alike,
/// plus the bridge's own records on each.
///
/// Returns a broadcast [Stream] of events from the `logEmitted` event channel.
///
/// Each call to this method creates a new [EventChannel], so it should
/// not be called multiple times for the same `instanceName`. To deliver
/// events to multiple listeners, call this method once and listen to the
/// returned broadcast stream multiple times instead.
Stream<NativeLogRecord> logEmitted({String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel logEmittedChannel = EventChannel(
      'dev.flutter.pigeon.colada_sdk.ColadaEventChannels.logEmitted$instanceName',
      pigeonMethodCodec);
  return logEmittedChannel.receiveBroadcastStream().map((dynamic event) {
    return event as NativeLogRecord;
  });
}
